const INDIAN_AIRPORTS = [
  // Metro Cities
  { city: 'Delhi', name: 'Indira Gandhi International Airport', code: 'DEL', state: 'Delhi' },
  { city: 'Mumbai', name: 'Chhatrapati Shivaji Maharaj International Airport', code: 'BOM', state: 'Maharashtra' },
  { city: 'Bengaluru', name: 'Kempegowda International Airport', code: 'BLR', state: 'Karnataka' },
  { city: 'Chennai', name: 'Chennai International Airport', code: 'MAA', state: 'Tamil Nadu' },
  { city: 'Kolkata', name: 'Netaji Subhas Chandra Bose International Airport', code: 'CCU', state: 'West Bengal' },
  { city: 'Hyderabad', name: 'Rajiv Gandhi International Airport', code: 'HYD', state: 'Telangana' },

  // Tier 1 Cities
  { city: 'Ahmedabad', name: 'Sardar Vallabhbhai Patel International Airport', code: 'AMD', state: 'Gujarat' },
  { city: 'Pune', name: 'Pune Airport', code: 'PNQ', state: 'Maharashtra' },
  { city: 'Jaipur', name: 'Jaipur International Airport', code: 'JAI', state: 'Rajasthan' },
  { city: 'Kochi', name: 'Cochin International Airport', code: 'COK', state: 'Kerala' },
  { city: 'Lucknow', name: 'Chaudhary Charan Singh International Airport', code: 'LKO', state: 'Uttar Pradesh' },
  { city: 'Goa', name: 'Goa International Airport (Dabolim)', code: 'GOI', state: 'Goa' },
  { city: 'Mopa', name: 'Manohar International Airport', code: 'GOX', state: 'Goa' },

  // Tier 2 Cities
  { city: 'Amritsar', name: 'Sri Guru Ram Dass Jee International Airport', code: 'ATQ', state: 'Punjab' },
  { city: 'Bhopal', name: 'Raja Bhoj Airport', code: 'BHO', state: 'Madhya Pradesh' },
  { city: 'Bhubaneswar', name: 'Biju Patnaik International Airport', code: 'BBI', state: 'Odisha' },
  { city: 'Chandigarh', name: 'Chandigarh International Airport', code: 'IXC', state: 'Punjab' },
  { city: 'Coimbatore', name: 'Coimbatore International Airport', code: 'CJB', state: 'Tamil Nadu' },
  { city: 'Dehradun', name: 'Jolly Grant Airport', code: 'DED', state: 'Uttarakhand' },
  { city: 'Guwahati', name: 'Lokpriya Gopinath Bordoloi International Airport', code: 'GAU', state: 'Assam' },
  { city: 'Indore', name: 'Devi Ahilyabai Holkar International Airport', code: 'IDR', state: 'Madhya Pradesh' },
  { city: 'Jabalpur', name: 'Dumna Airport', code: 'JLR', state: 'Madhya Pradesh' },
  { city: 'Jammu', name: 'Jammu Airport', code: 'IXJ', state: 'Jammu & Kashmir' },
  { city: 'Jodhpur', name: 'Jodhpur Airport', code: 'JDH', state: 'Rajasthan' },
  { city: 'Kannur', name: 'Kannur International Airport', code: 'CNN', state: 'Kerala' },
  { city: 'Kozhikode', name: 'Calicut International Airport', code: 'CCJ', state: 'Kerala' },
  { city: 'Leh', name: 'Kushok Bakula Rimpochee Airport', code: 'IXL', state: 'Ladakh' },
  { city: 'Mangaluru', name: 'Mangaluru International Airport', code: 'IXE', state: 'Karnataka' },
  { city: 'Nagpur', name: 'Dr. Babasaheb Ambedkar International Airport', code: 'NAG', state: 'Maharashtra' },
  { city: 'Patna', name: 'Jay Prakash Narayan International Airport', code: 'PAT', state: 'Bihar' },
  { city: 'Raipur', name: 'Swami Vivekananda Airport', code: 'RPR', state: 'Chhattisgarh' },
  { city: 'Ranchi', name: 'Birsa Munda Airport', code: 'IXR', state: 'Jharkhand' },
  { city: 'Shimla', name: 'Shimla Airport', code: 'SLV', state: 'Himachal Pradesh' },
  { city: 'Srinagar', name: 'Sheikh ul Alam International Airport', code: 'SXR', state: 'Jammu & Kashmir' },
  { city: 'Surat', name: 'Surat Airport', code: 'STV', state: 'Gujarat' },
  { city: 'Thiruvananthapuram', name: 'Trivandrum International Airport', code: 'TRV', state: 'Kerala' },
  { city: 'Tiruchirappalli', name: 'Tiruchirappalli International Airport', code: 'TRZ', state: 'Tamil Nadu' },
  { city: 'Udaipur', name: 'Maharana Pratap Airport', code: 'UDR', state: 'Rajasthan' },
  { city: 'Vadodara', name: 'Vadodara Airport', code: 'BDQ', state: 'Gujarat' },
  { city: 'Varanasi', name: 'Lal Bahadur Shastri International Airport', code: 'VNS', state: 'Uttar Pradesh' },
  { city: 'Visakhapatnam', name: 'Visakhapatnam Airport', code: 'VTZ', state: 'Andhra Pradesh' },

  // Smaller & Regional Airports
  { city: 'Agartala', name: 'Maharaja Bir Bikram Airport', code: 'IXA', state: 'Tripura' },
  { city: 'Agra', name: 'Agra Airport', code: 'AGR', state: 'Uttar Pradesh' },
  { city: 'Aizawl', name: 'Lengpui Airport', code: 'AJL', state: 'Mizoram' },
  { city: 'Allahabad', name: 'Prayagraj Airport', code: 'IXD', state: 'Uttar Pradesh' },
  { city: 'Aurangabad', name: 'Aurangabad Airport', code: 'IXU', state: 'Maharashtra' },
  { city: 'Bagdogra', name: 'Bagdogra Airport', code: 'IXB', state: 'West Bengal' },
  { city: 'Bhavnagar', name: 'Bhavnagar Airport', code: 'BHU', state: 'Gujarat' },
  { city: 'Bhuj', name: 'Bhuj Airport', code: 'BHJ', state: 'Gujarat' },
  { city: 'Deoghar', name: 'Deoghar Airport', code: 'DGH', state: 'Jharkhand' },
  { city: 'Dharamsala', name: 'Kangra Airport (Gaggal)', code: 'DHM', state: 'Himachal Pradesh' },
  { city: 'Dibrugarh', name: 'Dibrugarh Airport', code: 'DIB', state: 'Assam' },
  { city: 'Dimapur', name: 'Dimapur Airport', code: 'DMU', state: 'Nagaland' },
  { city: 'Diu', name: 'Diu Airport', code: 'DIU', state: 'Daman & Diu' },
  { city: 'Gorakhpur', name: 'Gorakhpur Airport', code: 'GOP', state: 'Uttar Pradesh' },
  { city: 'Hubli', name: 'Hubli Airport', code: 'HBX', state: 'Karnataka' },
  { city: 'Imphal', name: 'Bir Tikendrajit International Airport', code: 'IMF', state: 'Manipur' },
  { city: 'Itanagar', name: 'Donyi Polo Airport', code: 'HGI', state: 'Arunachal Pradesh' },
  { city: 'Jaisalmer', name: 'Jaisalmer Airport', code: 'JSA', state: 'Rajasthan' },
  { city: 'Jamnagar', name: 'Jamnagar Airport', code: 'JGA', state: 'Gujarat' },
  { city: 'Jorhat', name: 'Jorhat Airport', code: 'JRH', state: 'Assam' },
  { city: 'Kandla', name: 'Kandla Airport', code: 'IXY', state: 'Gujarat' },
  { city: 'Khajuraho', name: 'Khajuraho Airport', code: 'HJR', state: 'Madhya Pradesh' },
  { city: 'Kishangarh', name: 'Kishangarh Airport', code: 'KQH', state: 'Rajasthan' },
  { city: 'Kota', name: 'Kota Airport', code: 'KTU', state: 'Rajasthan' },
  { city: 'Kolhapur', name: 'Kolhapur Airport', code: 'KLH', state: 'Maharashtra' },
  { city: 'Kullu', name: 'Kullu Manali Airport (Bhuntar)', code: 'KUU', state: 'Himachal Pradesh' },
  { city: 'Lilabari', name: 'Lilabari Airport', code: 'IXI', state: 'Assam' },
  { city: 'Madurai', name: 'Madurai Airport', code: 'IXM', state: 'Tamil Nadu' },
  { city: 'Mysuru', name: 'Mysore Airport', code: 'MYQ', state: 'Karnataka' },
  { city: 'Nanded', name: 'Shri Guru Gobind Singh Ji Airport', code: 'NDC', state: 'Maharashtra' },
  { city: 'Nashik', name: 'Ozar Airport', code: 'ISK', state: 'Maharashtra' },
  { city: 'Pakyong', name: 'Pakyong Airport', code: 'PYG', state: 'Sikkim' },
  { city: 'Pondicherry', name: 'Puducherry Airport', code: 'PNY', state: 'Puducherry' },
  { city: 'Port Blair', name: 'Veer Savarkar International Airport', code: 'IXZ', state: 'Andaman & Nicobar' },
  { city: 'Porbandar', name: 'Porbandar Airport', code: 'PBD', state: 'Gujarat' },
  { city: 'Rajkot', name: 'Rajkot Airport (Hirasar)', code: 'RAJ', state: 'Gujarat' },
  { city: 'Salem', name: 'Salem Airport', code: 'SXV', state: 'Tamil Nadu' },
  { city: 'Shillong', name: 'Shillong Airport (Umroi)', code: 'SHL', state: 'Meghalaya' },
  { city: 'Silchar', name: 'Silchar Airport', code: 'IXS', state: 'Assam' },
  { city: 'Tezpur', name: 'Tezpur Airport', code: 'TEZ', state: 'Assam' },
  { city: 'Tirupati', name: 'Tirupati Airport', code: 'TIR', state: 'Andhra Pradesh' },
  { city: 'Tuticorin', name: 'Thoothukudi Airport', code: 'TCR', state: 'Tamil Nadu' },
  { city: 'Vijayawada', name: 'Vijayawada Airport', code: 'VGA', state: 'Andhra Pradesh' },
  { city: 'Warangal', name: 'Mamnoor Airport', code: 'WGC', state: 'Telangana' },
  { city: 'Belgaum', name: 'Belgaum Airport', code: 'IXG', state: 'Karnataka' },
  { city: 'Bikaner', name: 'Nal Airport', code: 'BKB', state: 'Rajasthan' },
  { city: 'Calicut', name: 'Calicut International Airport', code: 'CCJ', state: 'Kerala' },
  { city: 'Daman', name: 'Daman Airport', code: 'NMB', state: 'Daman & Diu' },
  { city: 'Deesa', name: 'Deesa Airport', code: 'DSA', state: 'Gujarat' },
];

export default INDIAN_AIRPORTS;